### ISSUE TITLE
2018.end() Challenge

### ISSUE THREAD

**Issue by JoseCage** [JoseCage/umappem24h#2]
Antes de mais faço votos de um bom final de ano para todos.

Tal como nas outras edições, o objetivo ao criar o desafio é incentivar as pessoas (desenvolvedores) a criar soluções (softwares, sites, apps móveis) em 24h.

Solução essa que pode ser levada em conta como um negócio ou portfólio. Considerando que para quem procura vagas é por sua vez obrigado a mostrar duas habilidades/skills. 

》》》》》》》》
O projeto fica a critério do desenvolvedor, o importante é desenvolver em 24h.

Para adicionar o projeto a participar somente como no exemplo abaixo:

Nome: Name here 
Projeto: Project name
Descrição: Description here
Link: #####

**Comment by JoseCage** [comment]
Nome: José Cage 
Projeto: Linka Faturas
Descrição: Sistema de geração de faturas e gestão de clientes, serviços.
Link: #####

**Comment by nelsonmfinda** [comment]
***Nome:*** _[Nelson Mfinda](http://nelsonmfinda.me)_
***Projecto:*** _Developers Stories_
***Descrição:*** ``` Um app baseado no Medium e na famosa stories das redes sociais. Com o Developers Stories, pessoas desenvolvedoras de software poderam partilhar histórias ou acontecimentos(Ex.: Aquele bug que tanto te incomodou hoje) relevantes no seu dia a dia como profissional de TI. ```
***Link:*** #######################################

**Comment by JoseCage** [comment]
Ideia top @nelsonmfinda 👌🏽👌🏽depois que colocar o projeto no GitHub ou qualquer plataforma vou dar uma olhada e colaborar com o que puder

**Comment by acidiney** [comment]
Nome: Acidiney Dias
Projecto: LivreCast
Descrição: `Projecto de podcast online no país com foco em tecnológia.... Estou com preguiça mais é isso!`
Link: livrecast.co.ao ( Ainda não regiistrado, por enquanto)

**Comment by JoseCage** [comment]
> Nome: Acidiney Dias
> Projecto: LivreCast
> Descrição: `Projecto de podcast online no país com foco em tecnológia.... Estou com preguiça mais é isso!`
> Link: livrecast.co.ao ( Ainda não regiistrado, por enquanto)

Boas @acidiney Vamos a isso

**Comment by nelsonmfinda** [comment]
> Nome: Acidiney Dias
> Projecto: LivreCast
> Descrição: `Projecto de podcast online no país com foco em tecnológia.... Estou com preguiça mais é isso!`
> Link: livrecast.co.ao ( Ainda não regiistrado, por enquanto)

É isso ai man @acidiney  :100: , @JoseCage  infelizmente ontem fiquei sem acesso a Internet.

**Comment by JoseCage** [comment]
> @JoseCage infelizmente ontem fiquei sem acesso a Internet.

Na boa @nelsonmfinda. Mas pudeste trabalhar em off pois não?

**Comment by JoseCage** [comment]
Depois de algumas horas perdidas tenho parte do app feito.

Link: https://linka.herokuapp.com

@nelsonmfinda e @acidiney não esqueci-me de vocês. Estava um pouco ocupado com as coisas pessoais e não publiquei o link antes.

**Comment by acidiney** [comment]
@JoseCage  Ta retornando 500, quando tento me cadastrar...
Ta ficando massa!

**Comment by JoseCage** [comment]
> @JoseCage Ta retornando 500

Opa @acidiney vou dar uma olhada para corrigir. Valeu

**Comment by acidiney** [comment]
> Opa @acidiney vou dar uma olhada para corrigir. Valeu

Fixe, depois avisa para testar

**Comment by JoseCage** [comment]
Não esquecendo que vocês dois ainda não mandaram.

**Comment by acidiney** [comment]
Link para o Livrecast https://livrecast.herokuapp.com

**Comment by JoseCage** [comment]
> Link para o Livrecast https://livrecast.herokuapp.com

O que já podemos usar ou testar no site/app?

**Comment by acidiney** [comment]
> O que já podemos usar ou testar no site/app?

Nada kkkk, os upload's são feitos por mim, e ainda me falta agendar com os primeiros convidados... Daqui a pouco vou fazer um commit eliminando algumas coisas desnecessárias!

**Comment by JoseCage** [comment]
> > O que já podemos usar ou testar no site/app?
> 
> Nada kkkk, os upload's são feitos por mim, e ainda me falta agendar com os primeiros convidados... Daqui a pouco vou fazer um commit eliminando algumas coisas desnecessárias!

Okay.

**Comment by JoseCage** [comment]
Hello devs
